// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl45vpw0W3JzE43g8fYqFs_HsYuCItyUU',
    appId: '1:135655983080:web:80c2a5ee6f0d26f34a865d',
    messagingSenderId: '135655983080',
    projectId: 'registrationbackend-4be50',
    authDomain: 'registrationbackend-4be50.firebaseapp.com',
    storageBucket: 'registrationbackend-4be50.firebasestorage.app',
    measurementId: 'G-THETGG5M07',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv5oRhJa-iS-YEEMw51xlAj8FrQXVbUW0',
    appId: '1:135655983080:android:4aba9ec9d5683cca4a865d',
    messagingSenderId: '135655983080',
    projectId: 'registrationbackend-4be50',
    storageBucket: 'registrationbackend-4be50.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGls-xwFNkIZ3Tvf6hxikCIigdxxsRsdk',
    appId: '1:135655983080:ios:3d1add514bf4c7e24a865d',
    messagingSenderId: '135655983080',
    projectId: 'registrationbackend-4be50',
    storageBucket: 'registrationbackend-4be50.firebasestorage.app',
    iosBundleId: 'com.example.registration',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGls-xwFNkIZ3Tvf6hxikCIigdxxsRsdk',
    appId: '1:135655983080:ios:3d1add514bf4c7e24a865d',
    messagingSenderId: '135655983080',
    projectId: 'registrationbackend-4be50',
    storageBucket: 'registrationbackend-4be50.firebasestorage.app',
    iosBundleId: 'com.example.registration',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBl45vpw0W3JzE43g8fYqFs_HsYuCItyUU',
    appId: '1:135655983080:web:da81e1688078a1714a865d',
    messagingSenderId: '135655983080',
    projectId: 'registrationbackend-4be50',
    authDomain: 'registrationbackend-4be50.firebaseapp.com',
    storageBucket: 'registrationbackend-4be50.firebasestorage.app',
    measurementId: 'G-475HZELST8',
  );
}
